apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: flux-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80 # 8080 for local test
      protocol: TCP
    - containerPort: 443
      hostPort: 443 # 8443 for local test
      protocol: TCP
  - role: worker
  - role: worker
