apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: production
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
  type: ClusterIP