apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: GNUPG_HOME
              value: /tmp
          volumeMounts:
            - name: sops-age
              mountPath: /tmp/sops-age/
              readOnly: true
          args:
            - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
            - --watch-all-namespaces=true
            - --log-level=info
            - --log-encoding=json
            - --enable-helm-controller=true
            - --decryption-provider=sops
            - --decryption-secret=sops-age
      volumes:
        - name: sops-age
          secret:
            secretName: sops-age