apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: api-app-image
  policy:
    semver:
      range: '>=1.0.0'
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+'
    extract: '$0'