apiVersion: v1
kind: Service
metadata:
  name: api-app-service
  namespace: production
  labels:
    app: api-app
    component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80 # почему не 8080?
      targetPort: http
      protocol: TCP
  selector:
    app: api-app
  sessionAffinity: None