apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: flux-system
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.flux-system:9090
        isDefault: true
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-stack.flux-system:3100
        editable: true