apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - loki-repo.yaml
  - loki-stack-release.yaml
  - grafana-datasources.yaml
  - grafana-ingress.yaml
  - grafana-allow-ingress.yaml