apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: loki-stack
      version: '2.10.x'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      enabled: true
      persistence:
        enabled: true
        size: 1Gi
    promtail:
      enabled: true
      config:
        clients:
          - url: http://loki-stack.flux-system:3100/loki/api/v1/push
    grafana:
      enabled: true
      adminPassword: "admin"
      service:
        type: ClusterIP
        port: 3000  # 80
        targetPort: 3000 # убрать
      persistence:
        enabled: true
        size: 1Gi
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://kube-prometheus-stack-prometheus.flux-system:9090
              isDefault: true          # ← Только этот default!
              editable: true
              jsonData:
                timeInterval: 30s
            - name: Loki
              type: loki
              access: proxy
              url: http://loki:3100
              isDefault: false         # ← НЕ default
              editable: true
            - name: Alertmanager
              type: alertmanager
              access: proxy
              url: http://kube-prometheus-stack-alertmanager.flux-system:9093
              isDefault: false         # ← НЕ default
              editable: true
              jsonData:
                implementation: prometheus
      sidecar:
        datasources:
          enabled: false       # ← ВАЖНО: отключить!
        dashboards:
          enabled: true        # Дашборды можно оставить
          label: grafana_dashboard
          folder: /tmp/dashboards
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
      dashboardsConfigMaps:
        default: grafana-dashboards