apiVersion: v1
kind: Secret
metadata:
    name: telegram-secrets
    namespace: flux-system
type: Opaque
stringData:
    bot-token: ENC[AES256_GCM,data:JwKUiWcB/IsZtCZe8sCjicEDfEx/YpFyth8bSqhGZQICWmO5vIrqc9kItf8bcw==,iv:MY00OXqM1fE7l3P9jSxKJYTWcrGi+3VRRNTXkyzQflU=,tag:PUWmxa5e3hdK76lxp439zw==,type:str]
    chat-id: ENC[AES256_GCM,data:57Wy9Umab1Ci,iv:e78zHmNDSKXPp6R7EtHzlpQJKnLrwLULJZpOfYthS6c=,tag:E8OkbwC1VL1kVPou6wI6Ig==,type:str]
sops:
    age:
        - recipient: age1vn0qveeefceqjx26373f2kcqeva8yw92jyttd8hafwcse2twldxs0lcn4c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWTJocjdPNkJFSVpHZjRE
            Z0lUUGM1djhnRzZtUjJFTUtXOXlSUm5MdFVrClhCblJaa0NJbTIxanh0blJQVnNZ
            TmRYcmZnTTVIbmZXZVMrVkJsbWRkRVEKLS0tIGh5ZEtERjdLV1pVQ0FNa3ViQzZK
            TTJ6NVdsY3lxMHpPajJ5RjRBWERPSHMKPOUbLAAdp85mNfvLf4WZ7MephjPlPB3J
            C2l/TCGy17SVkOyxkBaMxGkDRf0e3NLvFQMo4gC2UxbsYX9UK+L+bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T04:53:19Z"
    mac: ENC[AES256_GCM,data:1PR7Vvpb0GzSwBySllOxyPe7yMmMe+6TRKmi7zs+O7cF0Lc7qf4fK93bQg6rZYomkYFvrqa0yFJXiNHjk3OkAMCYQcb2XEsCKSMMnOIi4465jNNnm0WgUZbYCpjNaGr4W29aDyX9GUKksHl/PojT91+II/ZrqVIEpnPV21D29PA=,iv:ohlbvKc2B3uaNvfWRF3/OeqogVduzBYHeVIzsrtGPJs=,tag:yvSpQh6P4LIzPJ2TGsE5zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
