apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-bot-pvc
  namespace: flux-system
  labels:
    app: alertmanager-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi