apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.8.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  targetNamespace: ingress-nginx
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      # Settings for Kind
      replicaCount: 1
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      # Settings for production
      # replicaCount: 2
      # service:
      #   type: LoadBalancer

      metrics:
        enabled: true
        serviceMonitor:
          enabled: false

      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

      admissionWebhooks:
        enabled: true

      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

      config:
        log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'
        use-forwarded-headers: "true"