apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  namespace: production
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api-app
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "400m"
          env:
            - name: APP_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"