apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - target:
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    path: patches/sops-patch.yaml
secretRef:
  name: sops-age
